import argparse
str2bool = lambda x: x.lower() == "true"
parser = argparse.ArgumentParser()
parser.add_argument('--exp', type=str, default="benchmark")
# parser.add_argument('--data_root', type=str, default="/home/gpusharedata/rhb/fmri/output/ASD_NC_1207")
# parser.add_argument('--data_root', type=str, default="/home/sharedata/gpuhome/rhb/fmri/no_mean_data/PostProcessing/AAL/ROI_0")
parser.add_argument('--data_root', type=str, default='/home/sharedata/gpuhome/rhb/fmri/AAL_output/')
parser.add_argument('--epochs', type=int, default=800)
parser.add_argument('--batch_size', type=int, default=32)
parser.add_argument('--lr', type=float, default=0.001)
parser.add_argument('--lr_decay_factor', type=float, default=0.5)
parser.add_argument('--lr_decay_step_size', type=int, default=100)
parser.add_argument('--epoch_select', type=str, default='val_max')
parser.add_argument('--n_layers_feat', type=int, default=1)
parser.add_argument('--n_layers_conv', type=int, default=3)
parser.add_argument('--n_layers_fc', type=int, default=2)
parser.add_argument('--hidden', type=int, default=128)
parser.add_argument('--global_pool', type=str, default="sum")
parser.add_argument('--skip_connection', type=str2bool, default=False)
parser.add_argument('--res_branch', type=str, default="BNConvReLU")
parser.add_argument('--dropout', type=float, default=0)
parser.add_argument('--edge_norm', type=str2bool, default=False)
parser.add_argument('--with_eval_mode', type=str2bool, default=True)
parser.add_argument('--model', type=str, default="GCN")
parser.add_argument('--aug1', type=str, default="random2")
parser.add_argument('--aug_ratio1', type=float, default=0.2)
parser.add_argument('--aug2', type=str, default="random2")
parser.add_argument('--aug_ratio2', type=float, default=0.2)
parser.add_argument('--model_lr', type=str, default="0.001")
parser.add_argument('--model_epoch', type=str, default="100")
parser.add_argument('--model_name',type=str,default='GCN')
parser.add_argument('--dataset', type=str, default="fmri")
parser.add_argument('--semi_split', type=int, default=100)
parser.add_argument('--suffix', type=int, default=0)
# parser.add_argument('--model_dir',type=str,default='/home/gpusharedata/rhb/fmri/model/ASD_NC_GCN_1208')
parser.add_argument('--model_dir',type=str,default='/home/gpusharedata/rhb/fmri/SPA_model/')
parser.add_argument('--clf', type=str, default='ASD_NC')
parser.add_argument('--ts',type=int,default=64)
parser.add_argument('--fold_list',type=str,default='0,1,2,3')
parser.add_argument('--trainortest',type=str,default='test')
parser.add_argument('--continuetrain',type=str2bool,default=False)
parser.add_argument('--time_clf',type=str2bool,default=True)
parser.add_argument('--node_clf',type=str2bool,default=True)
parser.add_argument('--threshold',type=int,default=100) #图的阈值，稀疏化
# parser.add_argument('--subject_dir',type=str,default='/home/sharedata/gpuhome/rhb/fmri/no_detla_subject/AE.list')
parser.add_argument('--subject_dir',type=str,default='/home/gpusharedata/rhb/fmri/no_detla_subject/AE.list')
parser.add_argument('--ROI_num',type=int,default=0)
# parser.add_argument('--output_filename',type=str,default='/home/sharedata/gpuhome/rhb/fmri/AAL_output/ROI_0/')
parser.add_argument('--output_filename',type=str,default='/home/gpusharedata/rhb/fmri/no_mean_data/PostProcessing/Graph')
args = parser.parse_args()
